"""Added password field

Revision ID: 034391e31e1e
Revises: d2ad4011f925
Create Date: 2022-05-16 10:38:20.911840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034391e31e1e'
down_revision = 'd2ad4011f925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
