"""Url link added

Revision ID: 12a39b11797c
Revises: 695b7b30d5bc
Create Date: 2022-05-23 10:03:44.285471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a39b11797c'
down_revision = '695b7b30d5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('banner', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'banner')
    # ### end Alembic commands ###
