"""Profile Picture

Revision ID: 695b7b30d5bc
Revises: 1988082fd2f3
Create Date: 2022-05-21 11:47:17.236695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695b7b30d5bc'
down_revision = '1988082fd2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
